language: python

install: pip install -r requirements.txt

before_script:
 - python ./manage.py migrate
 - python manage.py collectstatic --noinput

script:
 - flake8 .
 - black --check .
 - coverage run --source=polls,mysite manage.py test

after_script:
 - coveralls